CREATE TABLE users (
    id CHAR(36) DEFAULT (UUID()) PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(60) NOT NULL,
    img_url VARCHAR(255),
    role INT NOT NULL,
    altura INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);