name: PR Develop to Homolog

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base homolog \
            --head develop \
            --title "[AUTO] Promote develop to homolog" \
            --body "Pull Request automático para homologação."
