name: PR Feature to Develop

on:
  push:
    branches:
      - "feature/**"

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base develop \
            --head "${GITHUB_REF_NAME}" \
            --title "[AUTO] Merge ${GITHUB_REF_NAME} into develop" \
            --body "Pull Request criado automaticamente da branch ${GITHUB_REF_NAME} para develop."
