name: PR Homolog to Main

on:
  push:
    branches:
      - homolog

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --base main \
            --head homolog \
            --title "[AUTO] Release homolog to main" \
            --body "Pull Request automático para versão final."
